# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corpusobject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catid', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('knownloc', models.BooleanField()),
                ('physical', models.NullBooleanField()),
                ('verbsaddress', models.CharField(max_length=200)),
                ('downloadable', models.NullBooleanField()),
                ('project', models.CharField(max_length=50)),
                ('corpustype', models.CharField(max_length=50)),
                ('language', models.TextField()),
            ],
        ),
    ]
